# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-11 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank='true', upload_to='static/')),
                ('bio', models.TextField(default='')),
            ],
        ),
    ]
