# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-14 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_instarecipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
